name: Build docker
on:
  push:
    branches:
      - master
      - dev
      - update-actions

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  trivy:
    runs-on: ubuntu-20.04
    container:
      image: docker.io/aquasec/trivy:latest
    steps:
      - uses: actions/checkout@v3
      - run: apk update
      - run: apk add make
      - run: trivy --version
      - run: sh ./trivy_scan_repo.sh

  build:
    runs-on: ubuntu-20.04
    needs: trivy
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: sudo apt update
      - run: wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
      - run: sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
      - run: docker pull ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME || true
      - run: docker build --cache-from ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME --build-arg CI_JOB_TOKEN --build-arg UBUNTU_VERSION=20.04 -t ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME .
      - run: if [ $GITHUB_REF_NAME = "main" ]; then docker tag ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME ghcr.io/$GITHUB_REPOSITORY:latest; fi
      - run: version=$(head -n 1 version.txt)
      - run: if [ $GITHUB_REF_NAME = "main" ]; then docker tag ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME ghcr.io/$GITHUB_REPOSITORY:$version; fi
      - run: sh ./check_docker.sh
      - run: docker push ghcr.io/$GITHUB_REPOSITORY --all-tags
