name: Trivy Scan and Build Docker
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  trivy_scan_repo:
    runs-on: ubuntu-20.04
    container:
      image: docker.io/aquasec/trivy:latest
    steps:
      - uses: actions/checkout@v3
      - run: apk update
      - run: apk add make
      - run: trivy --version
      - run: sh ./trivy_scan_repo.sh

  docker_build_push:
    runs-on: ubuntu-20.04
    needs: trivy_scan_repo
    permissions:
      contents: read
      packages: write
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: sudo apt update
      - run: wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
      - run: sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
      - run: docker pull ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME || docker pull ghcr.io/$GITHUB_REPOSITORY:dev || true

      - name: Build with branch name as cache if branch is main or dev
        if: github.ref_name == 'main' || github.ref_name == 'dev'
        run: docker build --cache-from ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME --build-arg UBUNTU_VERSION=20.04 -t ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME .
      - name: Build with dev as cache for rest of the branches
        if: github.ref_name != 'main' || github.ref_name != 'dev'
        run: docker build --cache-from ghcr.io/$GITHUB_REPOSITORY:dev --build-arg UBUNTU_VERSION=20.04 -t ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME .

      - run: if [ $GITHUB_REF_NAME = "main" ]; then docker tag ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME ghcr.io/$GITHUB_REPOSITORY:latest; fi
      - run: echo "version=$(head -n 1 version.txt)" >> $GITHUB_ENV
      - run: if [ $GITHUB_REF_NAME = "main" ]; then docker tag ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME ghcr.io/$GITHUB_REPOSITORY:$version; fi
      - run: sh ./check_docker.sh

      - name: Push only if branch name is main or dev
        if: github.ref_name == 'main' || github.ref_name == 'dev'
        run: docker push ghcr.io/$GITHUB_REPOSITORY --all-tags

  docker_image_check:
    runs-on: ubuntu-20.04
    needs: [trivy_scan_repo, docker_build_push]
    if: github.ref_name == 'main' || github.ref_name == 'dev'
    permissions:
      contents: read
      packages: read
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: sudo apt update
      - run: wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
      - run: sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
      - run: if [[ $GITHUB_REF_NAME == "main" ]]; then docker pull ghcr.io/$GITHUB_REPOSITORY:latest ; else docker pull ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME ; fi;
      - run: sh ./check_docker.sh
